/*
 * This source file was generated by the Gradle 'init' task
 */
package cat.uvic.teknos.dam.controlbox.main;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MessageUtilsTest {
    @Test void testGetMessage() {
    }
}
