/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation(project(":repositories"));
    implementation(project(":model"));


}



tasks.named("jar") {
    dependsOn("classes")
}

tasks.named("classes") {
    dependsOn("compileJava")
}
